server:
  port: 8080

logging:
  level:
    org:
      example:
        webfluxdemo: debug
      springframework:
        data: trace


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/webflux-demo
  main:
    web-application-type: reactive
