server:
  port: 8080

logging:
  level:
    org.org.example: debug
    org.springframework.data.mongodb: debug


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      uri: mongodb://root:secret@localhost:27017/webflux-demo
  main:
    web-application-type: reactive
