' 프로젝트 코드 내 엔티티 관계 다이어그램

@startuml

entity "image" as image {
  * **id: string <<PK>>**
  --
  * name: string - 파일명 (확장자 포함)
  * url : string - 이미지 URL
  * created_at: date - 생성일
  * is_deleted: boolean - 삭제여부
}

entity "post" as post {
  * **id: string <<PK>>**
  --
  * title: string - 제목
  * content: string - 내용
  * created_at: date - 생성일
  * created_by: string - 작성자
  * is_deleted: boolean - 삭제여부
}

@enduml
